version: '2'
services:
  db:
    container_name: mongo
    image: mongo:3.2.6
    ports:
      - "27017:27017"

  deploy:
    container_name: tomcat
    build: .
    ports:
      - "8080:8080"
    links:
      - db:mongo
